package com.olive.upi.transport;

import myunmn.C0059ao;
import org.npci.upi.security.services.CLServices;

/* compiled from: AxisPay */
/* loaded from: classes.dex */
public class TransportConstants {
    public static String API_BASE_URL;
    public static final String API_URL = null;
    public static final String AXIS_ORGID = null;
    public static final String BANKNAME = null;
    public static final String BANK_IS_NOT_REGISTERED = null;
    public static final String BANK_NOT_EXIST = null;
    public static final String BHARAT_QR = null;
    public static String BILLERPAY_UPIID;
    public static String BILLPAY_UPIID;
    public static final String BILL_PAYMENTS_BBPS = null;
    public static final String BILL_PAYMENTS_DTH = null;
    public static final String BILL_PAYMENTS_RC = null;
    public static final String CERT_HASH_SHA1 = null;
    public static final String CERT_HASH_SHA2 = null;
    public static final String CERT_HASH_SHA256 = null;
    public static final String CERT_HASH_SHA256_AUG2022 = null;
    public static final String CERT_HASH_SHA256_AUG_2023 = null;
    public static final String CERT_HASH_SHA256_NEW = null;
    public static final String CERT_HASH_SHA256_NOV_2023 = null;
    public static final String CERT_HASH_SHA256_SEPT2021 = null;
    public static final String EXCEPTION_CLSERVICE_DISCONNECTED = null;
    public static final String EXCEPTION_COMMON_LIB_REG_ERROR = null;
    public static final String EXCEPTION_CRED_CREATION_FAILED = null;
    public static final String EXCEPTION_DEVICE_DETAILS_NOT_FOUND = null;
    public static final String EXCEPTION_KEY_XML_NOT_LOADED = null;
    public static final String EXCEPTION_TOKEN_NOT_LOADED = null;
    public static final String EXCEPTION_TRUST_CREATION_FAILED = null;
    public static String FLRESPDESC;
    public static String FPRESPDESC;
    public static final String INSTACARD_APPLY_URL = null;
    public static final String INSTACARD_VIEW_URL = null;
    public static String KEY_CODE;
    public static Double MAX_AMOUNT_ALLOWED;
    public static int MAX_TOKEN_DAYS;
    public static final String NO_INTERNET = null;
    public static final String OFFER_URL = null;
    public static final String OS = null;
    public static final String PARAM_CHANNEL = null;
    public static final String PARAM_MERCHANT = null;
    public static final String PERSONAL_LOAN_URL = null;
    public static final String QR_SUBTAG_01 = null;
    public static final String QR_SUBTAG_02 = null;
    public static final String QR_SUBTAG_08 = null;
    public static final String QR_TAG_AADHAAR = null;
    public static final String QR_TAG_ACC_IFSC = null;
    public static final String QR_TAG_AM = null;
    public static final String QR_TAG_CU = null;
    public static final String QR_TAG_MC = null;
    public static final String QR_TAG_PA_MAM = null;
    public static final String QR_TAG_PN = null;
    public static final String QR_TAG_TN = null;
    public static final String QR_TAG_TR_URL = null;
    public static String REG_TYPE_DEVICE;
    public static String REG_TYPE_PASSCODE;
    public static final String RESULT_ACCOUNT_BLOCKED = null;
    public static final String RESULT_CUSTOMER_BLOCKED = null;
    public static final String RESULT_DEVICE_BLOCKED = null;
    public static final String RESULT_FL = null;
    public static final String RESULT_FP = null;
    public static final String RESULT_INSUFFICIENT_BALANCE = null;
    public static final String RESULT_INVALID_UPIID = null;
    public static final String RESULT_MANDATE_EXECUTEBEFORE = null;
    public static final String RESULT_MAX_WRONG_PIN_ATTEMPT = null;
    public static final String RESULT_NO_INTERNET = null;
    public static final String RESULT_NPCI_DEVICE_ERROR = null;
    public static final String RESULT_NPCI_ERROR = null;
    public static final String RESULT_SESSION_EXPIRED = null;
    public static final String RESULT_SUCCESS = null;
    public static final String RESULT_UNKNOWN = null;
    public static final String RESULT_UPDATE_AVAILABLE = null;
    public static final String RESULT_UPGRADE_REQUIRED = null;
    public static final String RESULT_USER_CANCELLED = null;
    public static final String RESULT_WRONG_MPIN = null;
    public static final String SAFETYNET_CHECK_URL = null;
    public static String SALT_DELIMETER;
    public static final String SETU_API_KEY = null;
    public static final String SETU_URL = null;
    public static final String SETU_USER_ID = null;
    public static final String SIGNING_KEY_HASH = null;
    public static final String TYPE_CUSTOMER = null;
    public static final String UNABLE_TO_PROCESS = null;
    public static final String UNAUTHORIZED = null;
    public static final String UPI_SCHEME_COLLECT = null;
    public static final String UPI_SCHEME_INTERNATIONAL_QR = null;
    public static final String UPI_SCHEME_MANDATE = null;
    public static final String UPI_SCHEME_PAY = null;
    public static final String VERSION = null;
    public static final String VPA_EXTN_AADHAAR = null;
    public static final String VPA_EXTN_IFSC = null;
    public static final String VPA_VERIFY_MCC = null;
    public static final String handler = null;
    public static CLServices mClservices;
    public static String regRandom;
    public static String regToken;
    public static String sk;
    public static final String tranidPrefix = null;

    static {
        C0059ao.a(TransportConstants.class, 124);
    }
}
